DROP SEQUENCE FREEBOARDSEQ;
DROP TABLE FREEBOARD;

CREATE SEQUENCE FREEBOARDSEQ;

CREATE TABLE FREEBOARD(
	FREEBOARDSEQ NUMBER NOT NULL,
	USERID VARCHAR2(30),
	FREEBOARDTITLE VARCHAR2(1000),
	FREEBOARDCONTENT VARCHAR2(4000),
	REGDATE DATE,
	READCOUNT NUMBER,
	CONSTRAINT FREEBOARD_FK FOREIGN KEY (USERID) REFERENCES MEMBERS (USERID),
	CONSTRAINT FREEBOARD_PK PRIMARY KEY (FREEBOARDSEQ)
);

INSERT INTO FREEBOARD
VALUES(FREEBOARDSEQ.NEXTVAL, 'TEST', '자유게시판.', '자유글', SYSDATE, 0);

SELECT FREEBOARDSEQ, USERID, FREEBOARDTITLE, FREEBOARDCONTENT, REGDATE
FROM FREEBOARD
ORDER BY FREEBOARDSEQ DESC;