DROP SEQUENCE NOTICESEQ;
DROP TABLE NOTICE;

CREATE SEQUENCE NOTICESEQ;

CREATE TABLE NOTICE(
	NOTICESEQ NUMBER NOT NULL,
	USERID VARCHAR2(30) NOT NULL,
	NOTICETITLE VARCHAR2(1000) NOT NULL,
	NOTICECONTENT VARCHAR2(4000) NOT NULL,
	USERROLE VARCHAR2(100) NOT NULL,
	REGDATE DATE NOT NULL,
	CONSTRAINT NOTICE_FK FOREIGN KEY (USERID) REFERENCES MEMBERS (USERID),
	CONSTRAINT NOTICE_PK PRIMARY KEY (NOTICESEQ)
);

INSERT INTO NOTICE
VALUES(NOTICESEQ.NEXTVAL, 'test1', 'Ǫ�� �̿� ��Ģ', '1. �Ƚ��ϰ� ����� �ֽñ� �ٶ��ϴ�.', '관리자', SYSDATE);


SELECT NOTICESEQ, USERID, NOTICETITLE, NOTICECONTENT, USERROLE, REGDATE
FROM NOTICE
ORDER BY NOTICESEQ DESC;