DROP SEQUENCE NOTICESEQ;
DROP TABLE NOTICE;

CREATE SEQUENCE NOTICESEQ;

CREATE TABLE NOTICE(
	NOTICESEQ NUMBER PRIMARY KEY,
	USERID VARCHAR2(100) NOT NULL,
	NOTICETITLE VARCHAR2(1000) NOT NULL,
	NOTICECONTENT VARCHAR2(4000) NOT NULL,
	USERROLE VARCHAR2(100) NOT NULL,
	REGDATE DATE NOT NULL,
	CONSTAINT FOREIGN KEY (NOTICE_USERID) REFERENCES MEMBER (USERID),
	CONSTAINT FOREIGN KEY (NOTICE_USERROLE) REFERENCES MEMBER (USERROLE)
);

INSERT INTO NOTICE
VALUES(NOTICESEQ.NEXTVAL, '관리자1', '푸실 이용 수칙', '1. 안심하고 사용해 주시길 바랍니다.', 'ADMIN', SYSDATE);


SELECT NOTICESEQ, USERID, NOTICETITLE, NOTICECONTENT, USERROLE, REGDATE
FROM NOTICE
ORDER BY NOTICESEQ DESC;