DROP SEQUENCE NOTICESEQ;
DROP TABLE NOTICE;

CREATE SEQUENCE NOTICESEQ;

CREATE TABLE NOTICE(
	NOTICESEQ NUMBER NOT NULL,
	USERID VARCHAR2(30) NOT NULL,
	NOTICETITLE VARCHAR2(1000) NOT NULL,
	NOTICECONTENT VARCHAR2(4000) NOT NULL,
	USERROLE VARCHAR2(100) NOT NULL,
	REGDATE DATE NOT NULL,
	USERNICKNAME VARCHAR2(100) NOT NULL,
	CONSTRAINT NOTICE_FK FOREIGN KEY (USERID) REFERENCES MEMBERS (userId),
	CONSTRAINT NOTICE_PK PRIMARY KEY (NOTICESEQ)
);

INSERT INTO NOTICE
VALUES(NOTICESEQ.NEXTVAL, 'test1', '푸실 이용 수칙', '1. 안심하고 사용해 주시길 바랍니다.', 'ADMIN', SYSDATE, '관리자입니다.');


SELECT NOTICESEQ, USERID, NOTICETITLE, NOTICECONTENT, USERROLE, REGDATE
FROM NOTICE
ORDER BY NOTICESEQ DESC;